[phases.setup]
nixPkgs = ["python310", "chromium", "chromedriver", "python310Packages.pip", "python310Packages.setuptools", "python310Packages.wheel"]
cmds = ["/nix/store/*-python3-*/bin/python3 -m pip install --no-cache-dir -r requirements.txt"]
